lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # Clé secrète JWT
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # Clé publique JWT
    pass_phrase: '%env(JWT_PASSPHRASE)%' # Phrase secrète pour la clé privée
    token_ttl: 3600 # Durée de validité du jeton JWT en secondes (ici, 1 heure)
